version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: dpin-uptime-db
    environment:
      POSTGRES_USER: dpin
      POSTGRES_PASSWORD: dpin123
      POSTGRES_DB: dpin_uptime
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 